### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by ltopchyi** [ltopchyi/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Reviewer28** [comment]
<h1 class="name">Donald Tramp </h1>
<div class="job">President of United States of America</div>
<ul class="contacts">
<li><a href="https://www.fb.com/DonaldTrump" rel="author" class="facebook">
<svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path id=""/></svg>
<span>DonaldTrump</span></a></li>

<li><a href="realDonaldTrump@whitehouse.gov" rel="author" class="">
<svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path id=""/></svg>
<span>realDonaldTrump@whitehouse.gov</span></a></li>

<li><a href="https://twitter.com/realDonaldTrump" rel="author" class="twitter">
<svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path id=""/></svg>
<span>realDonaldTrump</span></a></li>

<li><a href="https://www.instagram.com/realDonaldTrump/" rel="author" class="instagram">
<svg class="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path id=""/></svg>
<span>realDonaldTrump</span></a></li>
</ul>

**Comment by ltopchyi** [comment]
Good job!
