### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by ltopchyi** [ltopchyi/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Reviewer28** [comment]
<section>
<h3>Languages</h3>
<p class="tags small"><a href="/ru-ru" hreflang="ru" rel="alternate" class="language" lang="ru">&#x1f1f7;&#x1f1fa; <span>РУССКИЙ</span></a> <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span></p>
</section>



<section>
<h3>Skills</h3>
<p class="tags small">
NEGOTIATING COUNTING REMODELING WRITING ACING SINGING REPORTING INCORPORATING SELLING ADVERTISING HOSTING COMPETING TWITTING PARENTING GAMBLING DATING SUING ORGANIZING FUNDING DEBATING ADVISING PRESBYTERIANING</p>
</section>



<section>
<h3>Character</h3>
<p class="tags small">
ADJUSTED CALM AMBITIOUS COMPETITIVE SOCIABLE DIRECT HOSTILE CARELESS IGNORANT INQUISITIVE BOLD CONFIDENT MISCHIEVOUS CHARMING INTERESTING DARING COLORFUL LAZY SELF-PROMOTING</p>
</section>



<section>
<h3>Likes&#x1f603;</h3>
<p class="tags small bulleted">
<span class="tag"><a href="https://www.youtube.com/watch?v=u_aLESDql1U">BILLIONS</a></span> <span class="tag">FILET-O-FISH</span><span class="tag"> BIG MAC</span><span class="tag"><a href="https://www.youtube.com/watch?v=RDrfE9I8_hs"> CHINA</a></span> <span class="tag">QUARTER POUNDER</span> <span class="tag">DIET COKE </span><span class="tag">TARIFFS</span> <span class="tag">BIBLE </span><span class="tag">ARTOF DEAL </span><span class="tag">PATRIOTS</span> <span class="tag">BEAUTIFUL MODELS</span> <span class="tag">GOLD</span> <span class="tag">EAL ESTATE </span><span class="tag">WAR PROTESTERS</span> <span class="tag">CONSTRUCTION </span><span class="tag">RUSSIANS </span><span class="tag">BANKS </span><span class="tag">SPORTS</span><span class="tag">WOMEN</span> <span class="tag">MEXICO</span> <span class="tag">RED HAT</span> <span class="tag">KOREANS </span><span class="tag">GOLF</span><span class="tag"> EVERYBODY <a href="https://www.youtube.com/watch?v=0f9ysmciWUk">[1]</a><a href="https://www.youtube.com/watch?v=TTdmKaXAfAs"> [2]</a></span></p>
</section>



<section>
<h3>Dislikes&#x1f61e;</h3>
<p class="tags small bulleted">
<span class="tag">DOGS</span> <span class="tag">MEDIA</span> <span class="tag">CNN</span> <span class="tag">GERMANS</span> <span class="tag">MEXICANS</span> <span class="tag">IMMIGRANTS</span><span class="tag"> SHITHOLE COUNTRIES</span> <span class="tag">UNATTRACTIVE WOMEN</span> <span class="tag">BLACKS</span> <span class="tag">SUSHI</span> <span class="tag">HOT-DOGS</span> <span class="tag">ALCOHOL</span> <span class="tag">FRUIT</span> <span class="tag">CHRISTMAS</span> <span class="tag">PARTIES LIBERALS</span></p>
</section>

<section>
<h3>Wants&#x1f97a;</h3>
<p class="tags small bulleted">
<span class="tag">BE HEALTHY</span> <span class="tag">GROW A TREE</span> <span class="tag">BUILD TRUMP AIRPORT</span> <span class="tag">HAVE A TASTE</span> <span class="tag">DO A HARLEM SHAKE IN CONGRESS</span><span class="tag"> TO GOLF MORE OFTEN</span> <span class="tag">WIN ALL THE COURT SUITS</span></p></section>

**Comment by ltopchyi** [comment]
Good job!
